### ISSUE TITLE
multiple npmignore files

### ISSUE THREAD

**Issue by robertdunaway** [ljharb/npmignore#1]
I have a solution where I have 2 .npmignore files.  One packages only the bare essentials for creating a project.  The second is one directory higher and is intended to include everything beneath it.

What appears to be happening is when publishing at the higher level the lower level .npmignore settings are used.  This gives me the wrong package.

Is it possible to specify which .npmignore file to use or at least tell npm to ignore any .npmignore file not in the root directory of where the publish is occurring?

Thanks,
Bob

**Comment by jonschlinkert** [comment]
hmm, I don't see why not. it would be implemented in the CLI. however, I've been using the `files` property in package.json instead of npmignore files lately. I'd be happy to take a pr if you want to put something together
